[project]
name = "gheyret-asr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "librosa>=0.11.0",
    "soundfile>=0.13.1",
    "torch>=2.10.0",
    "torchvision>=0.25.0",
]
